// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXVxA_y9-GbGptY1HcaLdeODBZ_kyRelU',
    appId: '1:636965214764:web:d4b457582e429e2f140f89',
    messagingSenderId: '636965214764',
    projectId: 'mynotes-felipe-app',
    authDomain: 'mynotes-felipe-app.firebaseapp.com',
    storageBucket: 'mynotes-felipe-app.firebasestorage.app',
    measurementId: 'G-VS8D1QJ99F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1OupKL0r2tf3EnWosRSli6Gg3Fsv5DpE',
    appId: '1:636965214764:android:9f9d7d7ccfb20df9140f89',
    messagingSenderId: '636965214764',
    projectId: 'mynotes-felipe-app',
    storageBucket: 'mynotes-felipe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2xBXtXIMC2kkoy64y299l1A5tum7S3iU',
    appId: '1:636965214764:ios:c6f17e1cd2d4bfa5140f89',
    messagingSenderId: '636965214764',
    projectId: 'mynotes-felipe-app',
    storageBucket: 'mynotes-felipe-app.firebasestorage.app',
    iosBundleId: 'com.mynotes.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2xBXtXIMC2kkoy64y299l1A5tum7S3iU',
    appId: '1:636965214764:ios:c6f17e1cd2d4bfa5140f89',
    messagingSenderId: '636965214764',
    projectId: 'mynotes-felipe-app',
    storageBucket: 'mynotes-felipe-app.firebasestorage.app',
    iosBundleId: 'com.mynotes.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXVxA_y9-GbGptY1HcaLdeODBZ_kyRelU',
    appId: '1:636965214764:web:58527b5ea600e786140f89',
    messagingSenderId: '636965214764',
    projectId: 'mynotes-felipe-app',
    authDomain: 'mynotes-felipe-app.firebaseapp.com',
    storageBucket: 'mynotes-felipe-app.firebasestorage.app',
    measurementId: 'G-7TEKKMVZZY',
  );
}
